Document: gitid
Title: Debian gitid Manual
Author: <insert document author here>
Abstract: This manual describes what gitid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gitid/gitid.sgml.gz

Format: postscript
Files: /usr/share/doc/gitid/gitid.ps.gz

Format: text
Files: /usr/share/doc/gitid/gitid.text.gz

Format: HTML
Index: /usr/share/doc/gitid/html/index.html
Files: /usr/share/doc/gitid/html/*.html
